name: Build STM32 Project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  # run on tag creation
  create:
    tags:

  # enable manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noahp/stm32wba55-example:2025-02-24

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # submodules too
          submodules: recursive

      - name: Build project
        run: |
          /opt/st/stm32cubeide_1.17.0/stm32cubeide --launcher.suppressErrors -nosplash \
            -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
            -data /tmp/stm-workspace \
            -import "STM32CubeIDE"

          /opt/st/stm32cubeide_1.17.0/stm32cubeide --launcher.suppressErrors -nosplash \
            -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
            -data /tmp/stm-workspace \
            -build BLE_p2pServer/Debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BLE_p2pServer.artifacts
          # The output artifacts are BLE_p2pServer.elf, BLE_p2pServer.map, etc.
          path: STM32CubeIDE/Debug/BLE_p2pServer.*
